spring.application.name=TT360-app

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#url=jdbc:postgresql://db.fakyokvxyjhupopulcmt.supabase.co:5432/postgres
#username=postgres
#password=TT360#ProjectDB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.web-application-type=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect